#
# default job configuration 
#
# Note: this is a YAML file, indentation is important, TAB characters are not permitted.
#     You must use an exact number of spaces to denote each indentation level.
#     This file uses 4 space characters for each level.
#

default.properties:
    executor: RuntimeExec
    java_flags: -Xmx512m
    # flag to allow users to input arbitrary network file paths as value to input file input parameters
    #allow.input.file.paths: false
    # flag to enable batch execution of jobs from the run module web page
    allow.batch.process: false
    # flag to allow users to submit jobs, set this to false to prevent new jobs
    allow.new.job: true

    # the max number of files to display in uploaded files tab
    upload.maxfiles: 50
    upload.partition.size: 10000000
    upload.max.size: 20000000000
    upload.jumploader: true
    upload.purge.all: false
    upload.display.dirs: true
    
    # location for user data
    user.root.dir: "../users"
    # by default user data is stored in <user.root.dir>/<user.id>
    # this can be overridden with the 'gp.user.dir' property, Note: 'user.dir' is a java system property
    
    # location for user files uploaded directly to the server from the upload tab
    # by default, <user.root.dir>/<user.id>/user.uploads/
    # can be overridden with the 'user.upload.dir' property.
    # if there are server config errors, files are uploaded directly to java.io.tmpdir

    # Turn off input file displays
    display.input.results: false

    # for the file downloader, set the max file size (in bytes) to display inline in the web browser
    max.inline.size: 10000000
executors:
    # default executor for all jobs, it is included in GenePattern
    RuntimeExec:
        classname: org.genepattern.server.executor.RuntimeCommandExecutor
        configuration.properties:
            # the total number of jobs to run concurrently
            num.threads: 20
